// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiV1HealthData, GetApiV1HealthResponses, GetApiV1UsersMeData, GetApiV1UsersMeResponses, PostApiV1AuthGoogleExchangeData, PostApiV1AuthGoogleExchangeErrors, PostApiV1AuthGoogleExchangeResponses, PostApiV1AuthLogoutData, PostApiV1AuthLogoutErrors, PostApiV1AuthLogoutResponses, PostApiV1AuthRefreshData, PostApiV1AuthRefreshErrors, PostApiV1AuthRefreshResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const getApiV1Health = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1HealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1HealthResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/health',
    ...options
});

/**
 * Refresh Tokens
 */
export const postApiV1AuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthRefreshData, ThrowOnError>) => (options.client ?? client).post<PostApiV1AuthRefreshResponses, PostApiV1AuthRefreshErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Exchange Google Code
 */
export const postApiV1AuthGoogleExchange = <ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthGoogleExchangeData, ThrowOnError>) => (options.client ?? client).post<PostApiV1AuthGoogleExchangeResponses, PostApiV1AuthGoogleExchangeErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/auth/google/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const postApiV1AuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostApiV1AuthLogoutData, ThrowOnError>) => (options.client ?? client).post<PostApiV1AuthLogoutResponses, PostApiV1AuthLogoutErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Me
 */
export const getApiV1UsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1UsersMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1UsersMeResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});
