// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * GoogleExchangeRequest
 */
export type GoogleExchangeRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Code Verifier
     */
    code_verifier: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
};

/**
 * UserMeResponse
 */
export type UserMeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Picture Url
     */
    picture_url: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetApiV1HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostApiV1AuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthRefreshError = PostApiV1AuthRefreshErrors[keyof PostApiV1AuthRefreshErrors];

export type PostApiV1AuthRefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type PostApiV1AuthGoogleExchangeData = {
    body: GoogleExchangeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google/exchange';
};

export type PostApiV1AuthGoogleExchangeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthGoogleExchangeError = PostApiV1AuthGoogleExchangeErrors[keyof PostApiV1AuthGoogleExchangeErrors];

export type PostApiV1AuthGoogleExchangeResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type PostApiV1AuthGoogleExchangeResponse = PostApiV1AuthGoogleExchangeResponses[keyof PostApiV1AuthGoogleExchangeResponses];

export type PostApiV1AuthLogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type GetApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserMeResponse;
};

export type GetApiV1UsersMeResponse = GetApiV1UsersMeResponses[keyof GetApiV1UsersMeResponses];
